name: CI
on: [push, pull_request]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: CLI help
        run: python cli.py --help
      - name: Synthetic project demo
        run: |
          set -eux
          mkdir -p /tmp/demo && cd /tmp/demo
          git init .
          git config user.email demo@example.com
          git config user.name demo

          # docker-compose
          cat > docker-compose.yml <<'YML'
          version: "3.8"
          services:
            web:
              image: nginx:alpine
              ports:
                - "8080:80"
              depends_on:
                - db
            api:
              image: demo/api:latest
              depends_on:
                - db
            db:
              image: postgres:16
          YML

          # k8s manifests
          mkdir -p k8s
          cat > k8s/app.yaml <<'YML'
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: api
          spec:
            template:
              spec:
                containers:
                  - name: api
                    image: demo/api:latest
                    ports:
                      - containerPort: 3000
          ---
          apiVersion: v1
          kind: Service
          metadata:
            name: api
          spec:
            type: LoadBalancer
            ports:
              - port: 80
          ---
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: api
          YML

          # env hints
          echo "DATABASE_URL=postgres://user:pass@db:5432/app" > .env

          python $GITHUB_WORKSPACE/cli.py --root . --out ARCHITECTURE.md
          grep -q '```mermaid' ARCHITECTURE.md
          grep -q 'Compose' ARCHITECTURE.md
          grep -q 'Kubernetes' ARCHITECTURE.md
          grep -q 'External' ARCHITECTURE.md
          python $GITHUB_WORKSPACE/cli.py --root . --format mermaid --out ARCHITECTURE.mmd
          test -s ARCHITECTURE.mmd
